# Generated by Django 2.1.1 on 2018-10-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cityid',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
