# Generated by Django 2.1.1 on 2018-10-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('weather', '0004_auto_20181005_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='weather.Country'),
        ),
    ]
