# Generated by Django 2.1.1 on 2018-10-06 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('weather', '0005_city_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'default_permissions': ('add', 'change', 'delete')},
        ),
    ]
