# Generated by Django 2.1.1 on 2018-09-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sid',
            field=models.IntegerField(),
        ),
    ]
