# Generated by Django 2.1.1 on 2018-10-07 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='createdat',
            new_name='createdate',
        ),
    ]
