# Generated by Django 2.1.1 on 2018-10-07 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0003_auto_20181007_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='createdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
