# Generated by Django 2.0.7 on 2018-07-29 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='movetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 7, 29, 1, 38, 35, 276595)),
            preserve_default=False,
        ),
    ]
