# Generated by Django 2.1.1 on 2018-10-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
