# Generated by Django 2.1.1 on 2018-10-14 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameplay', '0003_auto_20181009_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_sent',
                                            to=settings.AUTH_USER_MODEL)),
                ('tuser',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_received',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
