# Generated by Django 2.1.1 on 2018-10-16 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('gameplay', '0004_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='message',
            field=models.CharField(blank=True, help_text='Its always good to add a friendly message.', max_length=300,
                                   verbose_name='Optional Message'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='tuser',
            field=models.ForeignKey(help_text='Please select the user you want to play game with.',
                                    on_delete=django.db.models.deletion.CASCADE, related_name='invitation_received',
                                    to=settings.AUTH_USER_MODEL, verbose_name='User to Invite'),
        ),
    ]
