# Generated by Django 2.1.1 on 2018-09-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('paradigm', models.CharField(max_length=20)),
                ('rank', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Language Django Rest API Learning',
                'db_table': 'Language',
                'ordering': ['-rank'],
            },
        ),
    ]
