# Generated by Django 2.1.1 on 2018-09-16 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('languages', '0002_auto_20180916_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popularity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previousrank',
                 models.IntegerField(blank=True, db_index=True, null=True, verbose_name='PreviousWeekRank')),
                ('rank', models.IntegerField(default=-999, verbose_name='Rank')),
            ],
        ),
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('languages', models.ManyToManyField(to='languages.Language')),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='popularity',
            field=models.ForeignKey(default=-999, on_delete=django.db.models.deletion.CASCADE,
                                    to='languages.Popularity'),
        ),
    ]
