# Generated by Django 2.1.1 on 2018-09-17 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('guestbook', '0004_auto_20180917_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmer',
            old_name='language',
            new_name='languages',
        ),
    ]
